name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: make setup
      run: make setup
    - name: go to emby
      run: cd spk/emby
    - name: make emby
      run: make apkg-wdarm
    - name: make distcheck
      run: make distcheck
