name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: prereq
      run: sudo dpkg --add-architecture i386 && sudo apt-get update
    - name: prereq2       
      run: sudo apt install autogen automake bc bison build-essential check cmake curl cython debootstrap expect flex g++-multilib gettext git gperf imagemagick intltool libbz2-dev libc6-i386 libcppunit-dev libffi-dev libgc-dev libgmp3-dev libltdl-dev libmount-dev libncurses-dev libpcre3-dev libssl-dev libtool libunistring-dev lzip mercurial ncurses-dev php pkg-config python3 python3-distutils scons subversion swig unzip xmlto zlib1g-dev
    - name: prereq3
      run: sudo pip install -U setuptools pip wheel httpie      
    - name: make setup
      run: make setup
    - name: make setup
      run: make setup
    - name: go to emby
      run: cd spk/emby
    - name: make emby
      run: make apkg-wdarm
    - name: make distcheck
      run: make distcheck
